### ISSUE TITLE
Blokowanie wiekszej liczby wideo

### ISSUE THREAD

**Issue by ernestwait** [TyDraniu/sportpl-autoplay-remove#1]
Cześć,
np na takiej stronie 
http://www.sport.pl/F1/1,96296,18854386,gp-singapuru-vettel-odbiera-rekord-hamiltonowi-lekka-zapasc.html
pod komentarzami też jest wideo i ten dodatek go nie zatrzymuje, możesz temu zaradzić?
pzdr

**Comment by TyDraniu** [comment]
Pokombinuję. Ten filmik dolny zawsze usuwałem Adblockiem, więc nawet go nie zauważyłem.

**Comment by TyDraniu** [comment]
Wytestujesz mi wersję 1.4? Załączyłem dodatek pod Releases. Jeszcze nie podpisany przez mozillę, ale to nie powinno przeszkadzać. Jak potwierdzisz, że działa, wgram do AMO.

**Comment by ernestwait** [comment]
Wygląda na to, że działa :smiley: przetestowałem na firefoxie. Ogólnie to ja korzystam z chroma to sobie przeklejam kod i daje jako user.js w tempermonkey
pzdr
